# Generated by Django 4.0.3 on 2022-03-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_department_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='employee_name',
        ),
    ]
