# Generated by Django 4.0.3 on 2022-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
