# Generated by Django 4.0.3 on 2022-03-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='employee_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='employee_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee'),
        ),
    ]
