# Generated by Django 4.0.3 on 2022-03-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_remove_team_department_name_remove_employee_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(to='organization.team'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
