# Generated by Django 4.0.3 on 2022-03-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_remove_employee_team_employee_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='team_name',
            field=models.ManyToManyField(to='organization.team'),
        ),
    ]
