# Generated by Django 4.0.3 on 2022-03-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_designation_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='employee_designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='department_name',
        ),
        migrations.AddField(
            model_name='department',
            name='teams',
            field=models.ManyToManyField(to='organization.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='organization.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.designation')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
            ],
        ),
    ]
